# If a service wants to use us, they'd add this product chart to requirements.yaml.
# Then they could override em-anno microservice chart to add their team to the s2s whitelist.
# Note that this would go in their product chart, not this one.

global:
  environment: saat
  subscriptionId: "bf308a5c-0624-4334-8ff8-8dca9fd43783"
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

postgresql:
  enabled: true

### EM SERVICES ###
em-anno:
  anno:
    postgresql:
      nameOverride: em-anno-db
    releaseNameOverride: chart-em-annotation-em-anno
    image: hmcts.azurecr.io/hmcts/em-anno:latest
    # TODO use real liveness path
    livenessPath: '/health'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://chart-em-annotation-em-anno-db:5432/emannotationapp'
      IDAM_API_BASE_URI: http://idam-api-idam-saat.service.core-compute-idam-saat.internal
      S2S_BASE_URI: http://chart-em-annotation-rpe-s2s
      DM_STORE_APP_URL: http://chart-em-annotation-dm-store

em-npa:
  npa:
    postgresql:
      nameOverride: em-npa-db
    releaseNameOverride: chart-em-annotation-em-npa
    image: hmcts.azurecr.io/hmcts/em-npa:latest
    # TODO use real liveness path
    livenessPath: '/health'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://chart-em-annotation-em-npa-db:5432/emnpa'
      IDAM_API_BASE_URI: http://idam-api-idam-saat.service.core-compute-idam-saat.internal
      DM_STORE_APP_URL: http://chart-em-annotation-dm-store
      EM_ANNO_APP_URL: http://chart-em-annotation-em-anno
      S2S_BASE_URI: http://chart-em-annotation-rpe-s2s

##### DEPENDENCIES #####
rpe-service-auth-provider:
  java:
    releaseNameOverride: chart-em-annotation-rpe-s2s
    image: hmcts.azurecr.io/hmcts/rpe-service-auth-provider:latest

dm-store:
  blobstorage:
    enabled: true
  java:
    postgresql:
      nameOverride: dm-store-db
    releaseNameOverride: chart-em-annotation-dm-store
    image: hmcts.azurecr.io/hmcts/dm-store:latest
    keyVaults:
      ccd:
        resourceGroup: ccd-shared
        secrets:
          - dm-store-storage-account-primary-connection-string
          - dm-store-storage-account-secondary-connection-string
    environment:
      IDAM_USER_BASE_URI: http://idam-api-idam-saat.service.core-compute-idam-saat.internal
      IDAM_S2S_BASE_URI: http://chart-em-annotation-rpe-s2s
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://chart-em-annotation-dm-store-db:5432/evidence'
      ENABLE_DB_MIGRATE: 'true'
      ENABLE_TTL: 'false'
