# If a service wants to use us, they'd add this product chart to requirements.yaml.
# Then they could override em-anno microservice chart to add their team to the s2s whitelist.
# Note that this would go in their product chart, not this one.

global:
  environment: demo
  subscriptionId: "bf308a5c-0624-4334-8ff8-8dca9fd43783"
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

tags:
  postgresql-pod: false                 # any chart specific postgres
  blobstorage: false                     # blob storage for dm-store

postgresql:
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE USER emannotationapp WITH PASSWORD 'emannotationapp';
      CREATE DATABASE emannotationapp WITH OWNER = emannotationapp ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE USER emnpa WITH PASSWORD 'emnpa';
      CREATE DATABASE emnpa WITH OWNER = emnpa ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE USER evidence WITH PASSWORD 'evidence';
      CREATE DATABASE evidence WITH OWNER = evidence ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  nameOverride: postgres-db
  persistence:
    enabled: false

### EM SERVICES ###
em-anno:
  anno:
    releaseNameOverride: chart-em-annotation-em-anno
    image: hmctspublic.azurecr.io/em/anno:latest
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://chart-em-annotation-release-1-postgres-db:5432/emannotationapp'
      IDAM_API_BASE_URI: https://idam-api.demo.platform.hmcts.net
      S2S_BASE_URI: http://chart-em-annotation-rpe-s2s
      DM_STORE_APP_URL: http://chart-em-annotation-dm-store

em-npa:
  npa:
    releaseNameOverride: chart-em-annotation-em-npa
    image: hmctspublic.azurecr.io/em/npa:latest
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://chart-em-annotation-release-1-postgres-db:5432/emnpa'
      IDAM_API_BASE_URI: https://idam-api.demo.platform.hmcts.net
      DM_STORE_APP_URL: http://chart-em-annotation-dm-store
      EM_ANNO_APP_URL: http://chart-em-annotation-em-anno
      S2S_BASE_URI: http://chart-em-annotation-rpe-s2s

##### DEPENDENCIES #####
rpe-service-auth-provider:
  java:
    releaseNameOverride: chart-em-annotation-rpe-s2s
    image: hmctspublic.azurecr.io/rpe/service-auth-provider:latest

dm-store:
  java:
    releaseNameOverride: chart-em-annotation-dm-store
    image: hmctspublic.azurecr.io/dm/store:latest
    keyVaults:
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://chart-em-annotation-release-1-postgres-db:5432/evidence'
      IDAM_USER_BASE_URI: https://idam-api.demo.platform.hmcts.net
      IDAM_S2S_BASE_URI: http://chart-em-annotation-rpe-s2s
      ENABLE_DB_MIGRATE: 'true'
      ENABLE_TTL: 'false'
