# If a service wants to use us, they'd add this product chart to requirements.yaml.
# Then they could override em-anno microservice chart to add their team to the s2s whitelist, as shown.
# Note that this would go in their product chart, not this one.

#em-anno:
#  environment:
#    S2S_NAMES_WHITELIST: amended list of services would go here

# what is this?
#tags:
#  cmc-claim-store-postgresql-pod: false # claim-store chart
#  cmc-citizen-frontend-pod: false       # claim-store chart
#  rpe-feature-toggle-api-pod: true      # citizen-frontend dep
#  postgresql-pod: false                 # any chart specific postgres

global:
  environment: saat
  subscriptionId: "bf308a5c-0624-4334-8ff8-8dca9fd43783"
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

### EM SERVICES ###
em-anno:
  em-anno:
    image: hmcts.azurecr.io/hmcts/em-anno:latest
    readinessDelay: 200 # plenty time for dependencies all start
    livenessDelay: 200 # plenty time for dependencies all start
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://chart-em-annotation-release-rpa-em-annotation-db:5432/emannotationapp?ssl=disable
      IDAM_API_BASE_URI: http://idam-api-idam-saat.service.core-compute-idam-saat.internal
      S2S_BASE_URI: http://rpe-service-auth-provider-saat.service.core-compute-saat.internal
      DM_STORE_APP_URL: http://dm-store-saat.service.core-compute-saat.internal
      IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider-saat.service.core-compute-saat.internal


em-npa:
  npa-app:
    image: hmcts.azurecr.io/hmcts/em-npa:latest
    readinessDelay: 200 # plenty time for dependencies all start
    livenessDelay: 200 # plenty time for dependencies all start
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://chart-em-annotation-release-rpa-npa-db:5432/emnpa?ssl=disable
      IDAM_API_BASE_URI: http://idam-api-idam-saat.service.core-compute-idam-saat.internal
      S2S_BASE_URI: http://rpe-service-auth-provider-saat.service.core-compute-saat.internal
      DM_STORE_APP_URL: http://dm-store-saat.service.core-compute-saat.internal
      EM_ANNO_APP_URL: http://em-anno-saat.service.core-compute-saat.internal
      IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider-saat.service.core-compute-saat.internal


