# If a service wants to use us, they'd add this product chart to requirements.yaml.
# Then they could override em-anno microservice chart to add their team to the s2s whitelist.
# Note that this would go in their product chart, not this one.

global:
  environment: saat
  subscriptionId: "bf308a5c-0624-4334-8ff8-8dca9fd43783"
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

### EM SERVICES ###
em-anno:
  em-anno:
    image: hmcts.azurecr.io/hmcts/em-anno:latest
    readinessDelay: 40
    readinessTimeout: 20
    readinessFailureThreshold: 20
    readinessPeriod: 15
    livenessDelay: 40
    livenessTimeout: 20
    livenessPeriod: 15
    livenessFailureThreshold: 20
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://chart-em-annotation-release-rpa-em-annotation-db:5432/emannotationapp?ssl=disable
      IDAM_API_BASE_URI: http://idam-api-idam-saat.service.core-compute-idam-saat.internal
      S2S_BASE_URI: http://rpe-service-auth-provider
      DM_STORE_APP_URL: http://dm-store-saat.service.core-compute-saat.internal


em-npa:
  npa-app:
    image: hmcts.azurecr.io/hmcts/em-npa:latest
    readinessDelay: 40
    readinessTimeout: 20
    readinessFailureThreshold: 20
    readinessPeriod: 15
    livenessDelay: 40
    livenessTimeout: 20
    livenessPeriod: 15
    livenessFailureThreshold: 20
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://chart-em-annotation-release-rpa-npa-db:5432/emnpa?ssl=disable
      IDAM_API_BASE_URI: http://idam-api-idam-saat.service.core-compute-idam-saat.internal
      EM_ANNO_APP_URL: http://em-anno
      S2S_BASE_URI: http://rpe-service-auth-provider
      #      Eventually switch over to using locally sourced this
      DM_STORE_APP_URL: http://dm-store-saat.service.core-compute-saat.internal

##### DEPENDENCIES #####
rpe-service-auth-provider:
  java:
    releaseNameOverride: rpe-service-auth-provider
    image: hmcts.azurecr.io/hmcts/rpe-service-auth-provider:latest

#dm-store:
#  java:
#    releaseNameOverride: dm-store
#    image: hmcts.azurecr.io/hmcts/dm-store:latest
#    environment:
#      IDAM_USER_BASE_URI: http://idam-api-idam-saat.service.core-compute-idam-saat.internal
#      IDAM_S2S_BASE_URI: http://rpe-service-auth-provider