# If a service wants to use us, they'd add this product chart to requirements.yaml.
# Then they could override em-anno microservice chart to add their team to the s2s whitelist, as shown.
# Note that this would go in their product chart, not this one.

#em-anno:
#  environment:
#    S2S_NAMES_WHITELIST: amended list of services would go here

# what is this?
#tags:
#  cmc-claim-store-postgresql-pod: false # claim-store chart
#  cmc-citizen-frontend-pod: false       # claim-store chart
#  rpe-feature-toggle-api-pod: true      # citizen-frontend dep
#  postgresql-pod: false                 # any chart specific postgres

global:
  environment: saat
  subscriptionId: "bf308a5c-0624-4334-8ff8-8dca9fd43783"
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

### EM SERVICES ###
em-anno:
  java:
    image: hmcts.azurecr.io/hmcts/em-anno:latest
    readinessDelay: 120 # plenty time for dependencies all start
    livenessDelay: 120 # plenty time for dependencies all start

em-npa:
  java:
    image: hmcts.azurecr.io/hmcts/em-npa:latest
    readinessDelay: 120 # plenty time for dependencies all start
    livenessDelay: 120 # plenty time for dependencies all start